# Generated by Django 5.1.7 on 2025-03-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
