# Generated by Django 5.1.7 on 2025-03-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_remove_movie_rating_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
