# Generated by Django 5.1.7 on 2025-03-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_movie_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='average_rating',
        ),
    ]
