# Generated by Django 5.1.7 on 2025-03-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_rename_rating_movie_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='average_rating',
            new_name='rating',
        ),
    ]
